GET http://localhost:5000/api/fruits/

###
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "1515151515151515",
    "email": "asdasdasdfasdsd@naver.com",
    "password": "testpassword"
}

###
POST http://localhost:5000/api/fruits/
Content-Type: application/json

{
    "name": "Orange",
    "amount" : 1,
    "info" : "Good"
}
###

DELETE http://localhost:5000/api/users/6058aa5343eaab7e7774dab2
###

PUT http://localhost:5000/api/fruits/6055b3dc49a6afd11e07c1d1
Content-Type: application/json

{
    "name": "Orange",
    "amount" :34,
    "info" : "tset"
}